### ISSUE TITLE
[Bug]: Can't sign creator after transfer authority 

### ISSUE THREAD

**Issue by LipLoody** [metaplex-foundation/metaplex#1799]
### Which package is this bug report for?

storefront

### Issue description

When I update the candy machine to transfer the authority to a wallet: AAA
The sign process (in JS not in CLI) executed by AAA fail with error message :  
`Error: Transaction failed: Incorrect account owner`
there you can find the transaction : https://solscan.io/tx/4TpJCaNYTCVcasuA83GmdNCwsvQEaMMmNvf13W6tfNNVMSJSWhCiAGFVxefeHG8L4yrDGjbVNrn2pNmFcd79XeV9?cluster=devnet

There you can find the candymachine show command:
``` 
...Candy Machine...
Key: FJqZKgoroNukG3HRUCjWWHkNFoPLYhMuGk6dAmeErc36
1st creator : 46Hx8ExdrpJj8gHqwghvDtx2ndV6XPsAPPFuW7V8oYvf
authority:  7pS1dZcGWBncf7oqfxbZ2ZCVzikbENpTDtLUhciiYx6E
wallet:  7pS1dZcGWBncf7oqfxbZ2ZCVzikbENpTDtLUhciiYx6E
tokenMint:  null
uuid:  FJqZKg
price:  0
itemsAvailable:  3000
itemsRedeemed:  1
goLiveDate:  1970-01-01T00:00:00.000Z
symbol:  LC
sellerFeeBasisPoints:  1500
creators: 
7pS1dZcGWBncf7oqfxbZ2ZCVzikbENpTDtLUhciiYx6E at 100 %
maxSupply:  0
retainAuthority:  true
isMutable:  false
hidden settings:  {
  name: 'Le Cheval',
  uri: 'https://arweave.net/n8yx7v-GYwM3I3k1XLuqSlWTjJc1OAutsuFvG8gQw9M',
  hash: [
     *********
  ]
}
No end settings detected
No captcha for this candy machine
whitelist settings: 
Mint:  WL7mAxS7rixLHJ2fcJrKeQZMnTR9JcLdHpj3mkF58zi
Mode:  { burnEveryTime: {} }
Presale:  false
Discounted Price:  N/A
```

the strange thing is when I get the state of candymachine like :
```
const program = new anchor.Program(idl, CANDY_MACHINE_PROGRAM, provider);

const state: any = await program.account.candyMachine.fetch(candyMachineId);
```
  
I have in the `state` the `creators.verified : true`

But after the mint the creator is not verified as we can see there: https://solscan.io/token/EFAJXN3NXp2amYvywGGPBj8Qv3UhCoHS2Km5typsorKH?cluster=devnet#txs

Step to reproduce:
- create candymachine with hidden settings
- update candy machine with the new authority 
- execute storefront function `sendSignMetadata(connection, wallet, CANDYMACHINE_ID)` with the wallet that have the authority 

### Relevant log output

```shell
Error: Transaction failed: Incorrect account owner
```

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue
